eureka:
  instance:
    prefer-ip-address: true          # always use IP instead of hostname
    ip-address: 127.0.0.1            # force localhost IP
    hostname: localhost              # fallback hostname
    instance-id: ${spring.application.name}:${server.port}  # unique ID

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
